<?php
/**
 * @var \Pledg\PledgPaymentGateway\Block\Checkout\Pay $block
 */
?>
<div id="container_pledg_form"></div>
<button id="trigger_pledg_form" style="display: none;"></button>
<script>
    let button = document.querySelector("#trigger_pledg_form");

    new Pledg(button, {
        ...<?= json_encode($block->getPledgData()); ?>,
        ...{
            containerElement: document.querySelector('#container_pledg_form'),
            showCloseButton: true,
            onSuccess: function (result) {
                window.location.replace('<?php echo $this->getUrl('checkout/onepage/success'); ?>');
            },
            onError: function (error) {
                console.log(error);
            },
            onCancel: function (error) {
                console.log(error);
            },
        }
    });
    button.click();
</script>
